# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{micahwedemeyer-acts_as_archive}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Winton Welsh"]
  s.date = %q{2010-11-28}
  s.default_executable = %q{acts_as_archive}
  s.email = %q{mail@wintoni.us}
  s.executables = ["acts_as_archive"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/acts_as_archive",
    "init.rb",
    "lib/acts_as_archive.rb",
    "lib/acts_as_archive/base.rb",
    "lib/acts_as_archive/base/adapters/mysql.rb",
    "lib/acts_as_archive/base/adapters/postgresql.rb",
    "lib/acts_as_archive/base/destroy.rb",
    "lib/acts_as_archive/base/restore.rb",
    "lib/acts_as_archive/base/table.rb",
    "lib/acts_as_archive/migration.rb",
    "rails/init.rb",
    "spec/acts_as_archive/base/destroy_spec.rb",
    "spec/acts_as_archive/base/restore_spec.rb",
    "spec/acts_as_archive/base/table_spec.rb",
    "spec/acts_as_archive/base_spec.rb",
    "spec/acts_as_archive/migration_spec.rb",
    "spec/db/config/database.mysql.yml",
    "spec/db/config/database.postgresql.yml",
    "spec/db/log/.gitignore",
    "spec/db/migrate/001_add_to_articles.rb",
    "spec/db/migrate_2/001_add_to_articles.rb",
    "spec/db/models/article.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/micahwedemeyer/acts_as_archive}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Don't delete your records, move them to a different table}
  s.test_files = [
    "spec/acts_as_archive/base/destroy_spec.rb",
    "spec/acts_as_archive/base/restore_spec.rb",
    "spec/acts_as_archive/base/table_spec.rb",
    "spec/acts_as_archive/base_spec.rb",
    "spec/acts_as_archive/migration_spec.rb",
    "spec/db/migrate/001_add_to_articles.rb",
    "spec/db/migrate_2/001_add_to_articles.rb",
    "spec/db/models/article.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3.0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rspec>, ["~> 1.3.0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rspec>, ["~> 1.3.0"])
  end
end

