# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{viximo_acts_as_archive}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Winton Welsh"]
  s.date = %q{2010-08-30}
  s.default_executable = %q{acts_as_archive}
  s.email = %q{mail@wintoni.us}
  s.executables = ["acts_as_archive"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/acts_as_archive",
     "init.rb",
     "lib/acts_as_archive.rb",
     "lib/acts_as_archive/base.rb",
     "lib/acts_as_archive/base/adapters/mysql.rb",
     "lib/acts_as_archive/base/adapters/postgresql.rb",
     "lib/acts_as_archive/base/destroy.rb",
     "lib/acts_as_archive/base/restore.rb",
     "lib/acts_as_archive/base/table.rb",
     "lib/acts_as_archive/migration.rb",
     "rails/init.rb",
     "spec/acts_as_archive/base/destroy_spec.rb",
     "spec/acts_as_archive/base/restore_spec.rb",
     "spec/acts_as_archive/base/table_spec.rb",
     "spec/acts_as_archive/base_spec.rb",
     "spec/acts_as_archive/migration_spec.rb",
     "spec/db/config/database.mysql.yml",
     "spec/db/config/database.postgresql.yml",
     "spec/db/log/.gitignore",
     "spec/db/migrate/001_add_to_articles.rb",
     "spec/db/migrate_2/001_add_to_articles.rb",
     "spec/db/models/article.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/Viximo/acts_as_archive}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Don't delete your records, move them to a different table}
  s.test_files = [
    "spec/acts_as_archive/base/destroy_spec.rb",
     "spec/acts_as_archive/base/restore_spec.rb",
     "spec/acts_as_archive/base/table_spec.rb",
     "spec/acts_as_archive/base_spec.rb",
     "spec/acts_as_archive/migration_spec.rb",
     "spec/db/migrate/001_add_to_articles.rb",
     "spec/db/migrate_2/001_add_to_articles.rb",
     "spec/db/models/article.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

